<?php
$data = array (
  0 => 
  array (
    'cat_id' => '3',
    'cat_name' => '种类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => '6',
  ),
  1 => 
  array (
    'cat_id' => '33',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '1',
    'cat_name' => '国家',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '9',
    'goods_num' => '5',
  ),
  3 => 
  array (
    'cat_id' => '5',
    'cat_name' => '酒具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '2',
    'cat_name' => '价格',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '6',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '6',
  ),
  5 => 
  array (
    'cat_id' => '20',
    'cat_name' => '澳大利亚',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '17',
    'cat_name' => '匈牙利',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '14',
    'cat_name' => '意大利',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '21',
    'cat_name' => '智利',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '18',
    'cat_name' => '加拿大',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '15',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '19',
    'cat_name' => '俄罗斯',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '16',
    'cat_name' => '西班牙',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '法国',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '26',
    'cat_name' => '200-400元',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '23',
    'cat_name' => '51-100元',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '27',
    'cat_name' => '440元以上',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '24',
    'cat_name' => '101-150元',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '25',
    'cat_name' => '151-200元',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '22',
    'cat_name' => '0-50元',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '10',
    'cat_name' => '浆果酒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '7',
    'cat_name' => '白葡萄酒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '11',
    'cat_name' => '啤酒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '8',
    'cat_name' => '香槟起泡酒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '6',
    'cat_name' => '红葡萄酒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '12',
    'cat_name' => '伏特加',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '9',
    'cat_name' => '冰酒',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '30',
    'cat_name' => '香槟杯',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '31',
    'cat_name' => '烈酒杯',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '28',
    'cat_name' => '启瓶器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  30 => 
  array (
    'cat_id' => '32',
    'cat_name' => '醒酒器',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '29',
    'cat_name' => '红酒杯',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '34',
    'cat_name' => '酒类杂志',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '35',
    'cat_name' => '酒类书籍',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>